version: '3'
services:
  web:
    build:
      context: . 
    ports:
      - "5050:5000"  # Mapea el puerto 5050 del host al puerto 5000 del contenedor
    environment:
      - GREETINGS=Hello Rubiko Tech!
